<?php

namespace SettingsBundle\Repository;

/**
 * ServresDatabasesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServresDatabasesRepository extends \Doctrine\ORM\EntityRepository
{
}
